### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList

### ISSUE THREAD

**Issue by JGeovani** [pop1030123/VideoEditor#2]
Hello @pop1030123 ,
Whenever I try to "Create new project" the application has stopped working. How can I solve?
Thanks,

12-26 10:40:35.423 30332-30363/com.android.videoeditor E/VEApiService: Terminating IntentProcessor-AudioServiceThread
12-26 10:40:35.424 30332-30364/com.android.videoeditor E/VEApiService: Terminating IntentProcessor-ThumbnailServiceThread
12-26 10:40:35.428 30332-30362/com.android.videoeditor E/VEApiService: Terminating IntentProcessor-VideoServiceThread
12-26 10:40:45.103 30332-31024/com.android.videoeditor E/AndroidRuntime: FATAL EXCEPTION: IntentProcessor-VideoServiceThread
                                                                         Process: com.android.videoeditor, PID: 30332
                                                                         java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.android.videoeditor-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libvideoeditor_jni.so"
                                                                             at java.lang.Runtime.loadLibrary(Runtime.java:366)
                                                                             at java.lang.System.loadLibrary(System.java:989)
                                                                             at android.media.videoeditor.MediaArtistNativeHelper.<clinit>(MediaArtistNativeHelper.java:47)
                                                                             at android.media.videoeditor.VideoEditorImpl.<init>(VideoEditorImpl.java:163)
                                                                             at android.media.videoeditor.VideoEditorFactory.create(VideoEditorFactory.java:65)
                                                                             at com.android.videoeditor.service.ApiService.processIntent(ApiService.java:1601)
                                                                             at com.android.videoeditor.service.ApiService$IntentProcessor.run(ApiService.java:4721)

**Comment by merchant4mumbai** [comment]
Same problem i m facing can u help me ?

**Comment by pop1030123** [comment]
@JGeovani  @merchant4mumbai    What's your phone model?

**Comment by pop1030123** [comment]
@JGeovani  @merchant4mumbai  maybe you can find some so libs in https://github.com/pop1030123/VideoEditorAPI .

**Comment by JGeovani** [comment]
@pop1030123 Moto G (2ª Gen) - Android 5.0.2

**Comment by merchant4mumbai** [comment]
Images to video using android

**Comment by merchant4mumbai** [comment]
Moto G (2ª Gen) - Android 5.0.2

**Comment by yangteng2013** [comment]
gogo2gogo

**Comment by ashishvirani** [comment]
Same problem i m facing can u help me ?
